### ISSUE TITLE
CPU usages is confusing 

### ISSUE THREAD

**Issue by Shuvrodas** [pivotal-cf/docs-metrics#112]
In Pcf Metrics container cpu usages is confusing. we see apps reporting CPU usage higher than 100%. I don’t believe it is an issue, but I don’t understand how that is calculated and/or reported, and I can’t explain to our customers.
https://docs.pivotal.io/pcf-metrics/1-5/using.html#container

**Comment by mlimonczenko** [comment]
Hello @Shuvrodas,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
