### ISSUE TITLE
mysql login command for metrics DB is incorrect

### ISSUE THREAD

**Issue by ywei2017** [pivotal-cf/docs-metrics#114]
The login wouldn't work:
```
mysql/6dd4a0e8-866b-4d5e-badd-28fbd7ae081a:~# mysql -u root
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

```

The correct syntax is:
```
mysql/6dd4a0e8-866b-4d5e-badd-28fbd7ae081a:~# mysql   -h localhost -P 3306 -S /var/vcap/sys/run/pxc-mysql/mysqld.sock -u root -p
Enter password:
```

Also the query is incorrect:
```
select count(*) from metrics.app_metric_identifier where timestamp > ((UNIX_TIMESTAMP() - 60) * POW(10, 3));
```
Something like the following will be work:
```
select count(*) from metrics.app_metric where timestamp_minute >  ( (unix_timestamp() - 180) / 60 )
```

This guide needs to be updated for 1.6. I believe it's a carryover from 1.4 days.
Thanks
Yansheng

**Comment by jbooherl** [comment]
Hi ywei2017, we recommend you connect to the database via the following: 
https://docs.pivotal.io/pcf-metrics/1-6/using.html#metrics-data

**Comment by jbooherl** [comment]
We can definitely definitely update the query.
