### ISSUE TITLE
Uninstall Metrics 1.4 should be accompanied by "Delete Apps" errand

### ISSUE THREAD

**Issue by pivotal-mark-higuera** [pivotal-cf/docs-metrics#115]
When customers Uninstall PCF Metrics 1.4 (line 41), they should ensure that the "Delete Apps" errand is enabled. Otherwise the apps will remain active and can generate excessive amounts of logging data.

**Comment by paigecalvert** [comment]
Hi @pivotal-mark-higuera, I checked in with Matt Rinehart on this, and he reminded me that PCF Metrics v1.4 is unsupported, and the v1.4 docs are PDF-ed (meaning we are no longer making updates to them). Closing this issue, but definitely let me know if this edit applied to Metrics 1.6 or 2.0 and I'll be sure to update those versions instead.
