### ISSUE TITLE
Custom Metrics

### ISSUE THREAD

**Issue by hananiel** [pivotal-cf/docs-metrics#119]
This [section](https://docs.pivotal.io/app-metrics/1-6/monitoringpcfmetrics.html#custom-metrics) states that to get custom metrics one must install the Metrics Forwarder tile - this linked [pivnet resource documentation](https://network.pivotal.io/products/p-metrics-forwarder) says this is not supported.

Other documentation like [here](https://docs.pivotal.io/app-metrics/1-6/using.html#custom) suggests that for later versions of PCF 2.5 and later, metrics registrar must be used instead of metrics forwarder. 

Question: is there an equivalent tile to be installed for registrar? Can you point to any change or history about this - the docs are very confusing because switching the PCF version to prior  in docs (2.5 and earlier, the metrics registrar page continues to show). 

At a minimum, It would be nice to see some clarification if nothing additional needs to be done for later versions of PAS, since navigating from there, you assume the document applies to current version.

**Comment by mlimonczenko** [comment]
Hello @hananiel,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
