### ISSUE TITLE
Ensure that... but what if it's not?

### ISSUE THREAD

**Issue by lynhines** [pivotal-cf/docs-metrics#122]
troubleshooting.html says:

Ensure that the output displays the following apps, each in a started state:

    metrics-ingestor
    metrics-queue

Great-- but what if something isn't in a started state-- what do I do then?  Here and elsewhere, would be great if any "Ensure that..." statements in the docs include a place to go if they aren't.

**Comment by mlimonczenko** [comment]
Hello @lynhines,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
