### ISSUE TITLE
v2.0.2 released without release notes

### ISSUE THREAD

**Issue by coffee-squirrel** [pivotal-cf/docs-metrics#142]
https://docs.pivotal.io/app-metrics/2-0/rn-ki.html

**Comment by jncd** [comment]
Thank you for letting us know! 
I'll look into what when wrong.

**Comment by jncd** [comment]
Hi @coffee-squirrel 
Thank you for reporting the missed release notes.
The release notes for the v2.0.2 release are now live. Thanks to @jbooherl.
https://docs.pivotal.io/app-metrics/2-0/rn-ki.html
