### ISSUE TITLE
"cf.system.events.crash","metric_type": "event" - It is creating as metric instead of event

### ISSUE THREAD

**Issue by Ambarisha-006** [pivotal-cf/docs-metrics#146]
https://docs.pivotal.io/app-metrics/1-6/api/monitors.html

curl -H "Authorization: $(cf oauth-token)" "https://monitors-api.sys.DOMAIN/api/v1/$(cf app APP_NAME --guid)/monitors" -d '{ "metric_name": "cf.system.events.crash","metric_type": "event","metric_unit": "per minute","name": "monitor_name","snooze_time_in_minutes": 1,"threshold_comparator": ">=","critical_threshold": 1,"warning_threshold": 1,"critical_webhook_url": "critical_webhook_url","critical_json_payload": "critical_json_payload","warning_webhook_url": "warning_webhook_url","warning_json_payload": "warning_json_payload" }'

It is creating as metric instead of event, due to this it not triggerring

**Note:**
Once this is created usign above curl command in PCF metrics, if we just go and edit(Without any change) and save  then its saving as event

**Comment by Ambarisha-006** [comment]
Can this be prioritized? Configuring crash alerts through API is important - when its configured and its not sending crash alerts due to above issue - then it is not useful

**Comment by mlimonczenko** [comment]
Hello @Ambarisha-006,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
