### ISSUE TITLE
1.3 - Elastic Search troubleshooting

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/docs-metrics#78]
The troubleshooting says to refer to the heap size under "Data Store" under PCF Metrics configuration of the tile.  That field isn't there, so perhaps there is a default and untunable value that must be respected under resources?

**Comment by agregory999** [comment]
also the troubleshooting refers to Elasticsearch Coordinator, which doesn't appear to exist under Resources

**Comment by seviet** [comment]
@mgadiya could you help us address these reported issues?

**Comment by mgadiya** [comment]
@agregory999 My apologies for such a late reply. Somehow I missed the github notifications in my inbox and just saw it while updating the install docs here. 

We removed data store config property as well ES co-ordinator nodes from 1.3.5 and greater and totally missed out in updating the docs to reflect that correctly.  I am making a change now to add that clarity.

**Comment by seviet** [comment]
Thanks @mgadiya for your doc update! Closing this.
