### ISSUE TITLE
1.3.8

### ISSUE THREAD

**Issue by mhottinger1** [pivotal-cf/docs-metrics#83]
The documentation for PCF 1.3.8 under the "Procedures for Scaling" section references the ability to update MySQL InnoDB Buffer Size in "Data Store" section of the tile, but the tile doesn't expose this field in 1.3.8.

**Comment by vikafed** [comment]
Hi @mhottinger1. Thanks for bringing this to our attention! We've update the Sizing PCF Metrics topic https://docs.pivotal.io/pcf-metrics/1-3/sizing.html#metrics-procedures. You don't need to do Step 4 if you are using PCF Metrics v1.3.5 or later. This configuration was automated.
