### ISSUE TITLE
sizing.html#small has invalid resource config

### ISSUE THREAD

**Issue by gokeefe** [pivotal-cf/docs-metrics#86]
The Metrics tile 1.4.2 won't let you choose the sizing recommendations suggested for a 'small' deployment. 

ElasticSearch Master must have at least 4 GB of memory
ElasticSearch Data must have >= 2 instances, 32 GB of persistent disk, and 4 GB of memory
Redis and MySQL Server jobs must each have 32 GB of persistent disk, and 4 GB of memory

![000876](https://user-images.githubusercontent.com/126059/34446040-4d9df6bc-ec95-11e7-90b6-b13da0e6e550.png)

**Comment by animatedmax** [comment]
Thanks, @gokeefe 
It looks like we addressed this issue at the beginning of January.
